name: Build and Deploy to Cloud Func

on:
  push:
    branches:
      - dev

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  REGION: us-central1
  RUN_TIME: go113
  MEMORY: 128MB
  TRIGGER_RESOURCE: raw-image-storage
  TRIGGER_EVENT: google.storage.object.finalize
  ENTRY_POINT: GenThumbnails
  FUNCTION_NAME: example-gen-thumbnails-func

jobs:
  setup-build-deploy:
    name: Setup, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          service_account_email: ${{ secrets.SA_EMAIL }}
          service_account_key: ${{ secrets.SA_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}

      # Deploy image to Cloud Run
      - name: Deploy
        run: |-
          gcloud functions deploy "$FUNCTION_NAME" \
            --trigger-resource "$TRIGGER_RESOURCE" \
            --trigger-event "$TRIGGER_EVENT" \
            --memory "$MEMORY" \
            --region "$REGION" \
            --entry-point "$ENTRY_POINT" \
            --project ${{ secrets.PROJECT_ID }} \
            --service-account ${{ secrets.SA_EMAIL }} \
            --runtime "$RUN_TIME" \
            --allow-unauthenticated
